### PR TITLE
Add other tasks' help descriptions

### PR DESCRIPTION
**Pull request by adomokos**
I ran `make help` and I did not find the `build` target listed in the
help menu. I thought this project does not have it, but after checking
the `Makefile`, I found that target.

This change provides help menu text for all other Makefile targets.

Before:
```
% make help
coverage                       Displays test coverage report
help                           Prints this help command
lint                           Runs the go code linter
test                           Runs application tests
```

After:
```
% make help
all                            Lints and runs the tests
build                          Builds the project
coverage                       Displays test coverage report
example-server                 Builds an example server
help                           Prints this help command
jwt-cli                        Builds a jwt cli
lint                           Runs the go code linter
test                           Runs application tests
```

### CODE REVIEW

**Comment by adomokos** [comment]
Not sure how the code coverage dropped, I only edited the `Makefile`.

**Comment by benjigoldberg** [comment]
@adomokos I'm also confused by the coverage drop. We'll investigate tomorrow.

/bump patch
/lgtm

**Comment by adomokos** [comment]
@benjigoldberg - can you please merge (maybe rebase) it for me?

**Pull request merged**
