### PR TITLE
SEAR-1285 enable gzip compression in server middleware

### PR DESCRIPTION
**Pull request by greg-mclain**
**Issue Link**
https://spothero.atlassian.net/browse/SEAR-1285

**Description**
Enable gzip compression

### CODE REVIEW

**Review by noahwill — APPROVED** [review]
nice! what does this gzip compression get us?

**Comment by greg-mclain** [comment]
> nice! what does gzip compression get us?

We'll be able to significantly reduce the size of the response payload getting sent over the network by compressing the JSON response payload.

**Pull request merged**
