### PR TITLE
make README work

### PR DESCRIPTION
**Pull request by dj80hd**
minor tweaks to make the build/run procedure in README work

### CODE REVIEW

**Comment by benjigoldberg** [comment]
Thanks for the PR @dj80hd! Was the `make` or `make build` command not creating the `example_server` binary for you? If so, could you post what it did output?

**Comment by dj80hd** [comment]
`make build` will build `./example_server`, but `make` alone will not.  

Possibly, since `make` defaults are `lint` and `test`, `test` should have a dependency on `build` ?

**Comment by benjigoldberg** [comment]
@dj80hd I like that suggestion -- thanks for finding this. If you make that change I can go ahead and get it merged.

Thanks for the contribution!

**Comment by dj80hd** [comment]
glad to help @benjigoldberg -- this is a great idea

**Pull request merged**
